### PR TITLE
repro improvements

### PR DESCRIPTION
**Pull request by jvalleroy**
- Use augeas to modify config with Php lens.
  - (I didn't find a way to make this work for the LetsEncrypt configuration though.)
- Add new domain name (and remove old domain name) automatically, using admin web panel.
- Use any new LetsEncrypt certificate that matches the current domain name. Stop using when revoked.
- Also setup domain and LE cert during module setup, if available.
  - It may be a few seconds before the admin web panel is available, so wait and retry.

### CODE REVIEW

**Comment by SunilMohanAdapa** [comment]
This is quite nice.  Just today we have tested video calling with SIP.

**Comment by jvalleroy** [comment]
Since it will be fairly complicated to get LDAP users integrated with repro, would it make sense to synchronize the repro users with plinth users? (Similar to how the domain is synchronized in this PR.)

**Comment by SunilMohanAdapa** [comment]
On 09/07/2016 01:08 AM, James Valleroy wrote:
> Since it will be fairly complicated to get LDAP users integrated with
> repro, would it make sense to synchronize the repro users with plinth
> users? (Similar to how the domain is synchronized in this PR.)
> 

I believe the effort to connect repro to LDAP will be on the similar
lines of doing user sync with repro.  In addition, user syncing could
lead to lot of edge cases and lot of maintenance effort in the long run.

-- 
Sunil

**Comment by jvalleroy** [comment]
I pushed a branch https://github.com/jvalleroy/Plinth/tree/repro-improvements-2 which has been rebased to master, and resolved merge conflicts.

**Comment by jvalleroy** [comment]
Repository moved to https://salsa.debian.org/freedombox-team/freedombox.

**Pull request closed without merging**
