### PR TITLE
Monkey authentication - Phase 1

### PR DESCRIPTION
**Pull request by SunilMohanAdapa**
This pull request implements setting up Monkeysphere validation agent configuring Apache for it and managing it's list of certifiers.  The menu item to reach monkeysphere authentication UI is currently disabled and some rough edges exist.

Phase 2 is to use mod-auth-pubtkt to setup actual authentication into FreedomBox services with the help of email field.

### CODE REVIEW

**Comment by jvalleroy** [comment]
One issue when first accessing the authentication page:
```
[2016-10-01 13:30:38,024] plinth.actions ERROR    Error executing command - ['sudo', '-n', '/usr/share/plinth/actions/monkeysphere', 'auth-get-certifiers'], , No passwd entry for user 'msva-www'
Traceback (most recent call last):
  File "/usr/share/plinth/actions/monkeysphere", line 464, in <module>
    main()
  File "/usr/share/plinth/actions/monkeysphere", line 460, in main
    subcommand_method(arguments)
  File "/usr/share/plinth/actions/monkeysphere", line 202, in subcommand_auth_get_certifiers
    output = _run_gpg_command('gpg --list-keys --with-colon')
  File "/usr/share/plinth/actions/monkeysphere", line 190, in _run_gpg_command
    input=input, stdout=subprocess.PIPE, check=True)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['su', '-c', 'gpg --list-keys --with-colon', 'msva-www']' returned non-zero exit status 1

[2016-10-01 13:30:38,024] django.request ERROR    Internal Server Error: /plinth/sys/monkeysphere/authentication/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/Plinth-0.11.0-py3.5.egg/plinth/modules/monkeysphere/views.py", line 161, in authentication
    status = get_auth_status()
  File "/usr/local/lib/python3.5/dist-packages/Plinth-0.11.0-py3.5.egg/plinth/modules/monkeysphere/views.py", line 211, in get_auth_status
    output = actions.superuser_run('monkeysphere', ['auth-get-certifiers'])
  File "/usr/local/lib/python3.5/dist-packages/Plinth-0.11.0-py3.5.egg/plinth/actions.py", line 118, in superuser_run
    return _run(action, options, input, async, True)
  File "/usr/local/lib/python3.5/dist-packages/Plinth-0.11.0-py3.5.egg/plinth/actions.py", line 180, in _run
    raise ActionError(action, output, error)
plinth.errors.ActionError: ('monkeysphere', '', 'No passwd entry for user \'msva-www\'\nTraceback (most recent call last):\n  File "/usr/share/plinth/actions/monkeysphere", line 464, in <module>\n    main()\n  File "/usr/share/plinth/actions/monkeysphere", line 460, in main\n    subcommand_method(arguments)\n  File "/usr/share/plinth/actions/monkeysphere", line 202, in subcommand_auth_get_certifiers\n    output = _run_gpg_command(\'gpg --list-keys --with-colon\')\n  File "/usr/share/plinth/actions/monkeysphere", line 190, in _run_gpg_command\n    input=input, stdout=subprocess.PIPE, check=True)\n  File "/usr/lib/python3.5/subprocess.py", line 708, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command \'[\'su\', \'-c\', \'gpg --list-keys --with-colon\', \'msva-www\']\' returned non-zero exit status 1\n')
```
I guess the msva-www user needs to be created during module setup?

**Comment by SunilMohanAdapa** [comment]
When we enable authentication using monkeysphere using the checkbox, the setup process happens.  However, since the listing of certifiers is in the same page, this is failing and not letting us get to the point of enabling authentication.  When I built it, I built the two pieces separately and didn't face the problem.

One solution could be to not show the certifiers part of the page unless the authentication is enabled.  Perhaps it is better to run the two authentication setup steps (service file and user creation) during module setup as you have suggested.  I will update my patch accordingly. Meanwhile, see if you can get past this and review the rest of the patch.

I really wish the msva package would have a msva-web package that would create the user and systemd service file.  I shall be submitting detailed bug reports soon.

**Comment by SunilMohanAdapa** [comment]
I have realized the if the configuration of a a virtualhost required for SSL is factored out into an include file, and also if the monkeysphere configuration is an include file inside that, then we can avoid the mess of passing list of domains as argument to enable/disable and have a more robust configuration.  I will make this change also.

**Comment by jvalleroy** [comment]
Repository moved to https://salsa.debian.org/freedombox-team/freedombox.

**Pull request closed without merging**
